# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sgpuserverless
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sgpu
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sgpu-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  logs:
    lambda:
    logFormat: JSON
    applicationLogLevel: ERROR
    systemLogLevel: INFO
    # logGroup: /aws/lambda/global-log-group
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::export-excel-sgpu/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - arn:aws:sqs:us-east-1:013271978441:ably-notifications
        - arn:aws:sqs:us-east-1:013271978441:email-queue
        - arn:aws:sqs:us-east-1:013271978441:excel-export-queue
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - lambda:InvokeFunction
      Resource: "*"

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes # this should go before
  - serverless-plugin-include-dependencies

build:
  esbuild: false

functions:
  getProyectosExport:
    handler: functions/getProyectosExport/handler.handler
    events:
      - http:
          path: getProyectosExport
          method: post
          cors: true
  generateExcelQueue:
    handler: functions/generateExcelQueue/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:013271978441:excel-export-queue
          batchSize: 1
  ablyNotificationQueue:
    handler: functions/ablyNotificationQueue/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:013271978441:ably-notifications
          batchSize: 10
  sendEmailQueue:
    handler: functions/sendEmailQueue/handler.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:013271978441:email-queue
          batchSize: 10
